### ISSUE TITLE
SetDataType() is protected, not public

### ISSUE THREAD

**Issue by ted537** [hgupta9/FluentFTP#107]
Maybe there's something I'm missing here, but it seems like changing the data transfer type should be accessible without subclassing FtpClient.

**Comment by hgupta9** [comment]
Just out of curiosity why do you need to do this? I can either make it public or leave it as is (if its wrong usage).

**Comment by ted537** [comment]
I just saw it in the documentation and assumed it was meant to be public, so that it can be used on an instance of FtpClient.

Just double checking that I actually understand what this function does: If I want to transfer files in binary mode, I have to call SetDataType(), right?

**Comment by hgupta9** [comment]
Good points, but nah, binary mode is used as default when you transfer files with the [high level API](https://github.com/hgupta9/FluentFTP#file-transfer). The only time you need to use it is when you use OpenRead/OpenWrite and even they have an arg that must be used. Removed from docs since its causing confusion.
