### ISSUE TITLE
Would it be possible to make a Net Standard 1.4 version?

### ISSUE THREAD

**Issue by kylone** [hgupta9/FluentFTP#112]
I'm wondering if there's a blocker for having the .Net Standard version of this library use Standard 1.4. This would allow it to be a single library that can be used in a .Net Standard library that I'm working on,

**Comment by hgupta9** [comment]
Basically we support FTPS (SSL/TLS) via the SslStream which is only present in 1.6, I think. I'm not sure since I'm not a .NET core export. I just compiled the thing for .NET core and pushed it to nuget. 

**Method A**
So, back to your question, yes we can support .NET 1.4 but we need this:

- **System.Net.Security** Version 4.3.0.0 (if we can use an older version of this then .NET 1.4 support is possible)

**Method B**
Add compile flags for .NET 1.4 and 1.6 separately and include SSL support only in 1.6. I'm not sure how to do this but if you can get a "hello world" example working in VS 2017, or fork and modify FluentFTP for this then it would be great. At minimum you will have to revert [this](https://github.com/hgupta9/FluentFTP/commit/6f31a636acfa5b2fed4ad2f65f99582eae44c7d4).

**Comment by hgupta9** [comment]
FluentFTP is now compiled for .Net Standard 1.4 and UWP 10.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/
