### ISSUE TITLE
AccessViolationException in FtpSocketStream when connecting

### ISSUE THREAD

**Issue by vishalpatel-te** [hgupta9/FluentFTP#145]
![image](https://user-images.githubusercontent.com/17013023/28590396-ed100c9c-714f-11e7-96d6-cc16e3fcca8a.png)

On one of our dev environment we are getting error that forces the process to exist.
I have tried to set the FTPTrace flags to false with no affect.
            FtpTrace.FlushOnWrite = false;
            FtpTrace.LogFunctions = false;
            FtpTrace.LogIP = false;
            FtpTrace.LogPassword = false;
            FtpTrace.LogUserName = false;
            FtpTrace.LogPrefix = false;

Also tried, 
            FtpTrace.AddListener(new TextWriterTraceListener("log_file.txt")
            {
                Filter = new EventTypeFilter(SourceLevels.Error)
            });

But getting same error all the time. Any help regarding this would be appreciated.

Same code gives no error on other developer's machine.

**Comment by hgupta9** [comment]
Disabling the tracing will not solve the error! Its like disabling the logging system! The error is caused by the socket stream, not by the tracing/logging system! I don't know what the error is. Perhaps you should remove all the lines you showed above and enable logging on console (see the FAQ).. and then see at what point the error occurs. More than that there is nothing I can do from the armchair. Search google for AccessViolationException in Stream... FtpSocketStream is the main socket handling class, it has NO unsafe code so I'm not sure what is causing the AccessViolationException.. also the code in Connect() is very simple.. you can see for yourself in the source code. Maybe try running the debug version, it will give line numbers of the error as well...

https://we.tl/MQBg8vxViq

**Comment by vishalpatel-te** [comment]
I am currently on 17.5.8 versrion before. Updating to 17.6.0 did not resolve the issue either. But the one you provided in link above did. So something is getting missed between DEBUG and RELEASE versions. 
May be .Net compiler is optimizing something it should not.
Will use the debug dll for now.

**Comment by albertop** [comment]
Hi, all:

I am getting the exact exception while doing .Connect() while using the version 17.6.1 from nuget.

My app targets net40.  Could be the case that the app downloaded from Nuget is not for NET4?

Would you help me solve this?

Unhandled Exception: System.AccessViolationException: Attempted to read or write
 protected memory. This is often an indication that other memory is corrupt.
   at FluentFTP.FtpTrace.Write(FtpTraceLevel eventType, String message)
   at FluentFTP.FtpClient.Connect()
   at TV2LogConsolidator.Program.Send(SendParameters sendParams) in C:\LogConsolidator\Send.cs:line 275
   at TV2LogConsolidator.Program.Send(String sendConfigFile) in C:\LogConsolidator\Send.cs:line 28
   at NConsoler.Consolery.InvokeMethod(MethodInfo method)
   at NConsoler.Consolery.RunAction()
   at NConsoler.Consolery.Run(Type targetType, String[] args, IMessenger messeng
er, Notation notationType)
   at NConsoler.Consolery.Run(Type targetType, String[] args)
   at TV2LogConsolidator.Program.Main(String[] args) in C:\LogConsolidator\Program.cs:line 71

Alberto.
