### ISSUE TITLE
FtpRemoteExists.Overwrite now performs a delete+create rather than in-place overwrite

### ISSUE THREAD

**Issue by mcrossley** [hgupta9/FluentFTP#1586]
**FluentFTP Version:**  50.0.1

I have users complaining that the latest version of FluentFTP is messing with the file permissions on the FTP server.

They are using the file overwrite option, from the logs I have determined that the overwrite option now performs a file delete then create. The previous version would perform an in-place overwrite.

Because it deletes the target file and creates a new file, any customised file permissions on the target file are lost, previously they were retained.

The source code that is doing this is here (there is similar code in the async client)...

FluentFTP/Client/SyncClient/UploadFileInternal.cs
```
		protected FtpStatus UploadFileInternal(Stream fileData, string localPath, string remotePath, bool createRemoteDir,
...
89					else if (existsMode == FtpRemoteExists.Overwrite) {

						// delete the remote file if it exists and we need to overwrite
						if (fileExists) {
							DeleteFile(remotePath);
						}
					}

```

Is there any way to force FluentFTP to go back to the old behaviour of performing an in-place overwrite?

**Comment by FanDjango** [comment]
> They are using the file overwrite option, from the logs I have determined that the overwrite option now performs a file delete then create. The previous version would perform an in-place overwrite.

Sadly, you have not included two crucial pieces of information.

"_from the logs_ I have determined that the overwrite option **now** performs a file delete then create"

Since I know the code a little bit, I believe you. But we always like logs to see **even more**.

You say "**now" it "performs a file delete then create". That code has been in there unchanged for 2 years. **From what prior version are you basing the comparison in behaviour?**.

>  The previous version ...

Pray tell, what this previous version would be?

There some possibles other places that might have caused this change in behaviour. Perhaps FtpRemoteExists.Nocheck might be better? That logic might have changed, I would need to research.

**Comment by mcrossley** [comment]
Sorry, i just looked up the version they were upgrading from, it is a pretty old version of both my program and FluentFTP - 32.3.1

I am using the Client.UploadStream(myStream, remoteFile) high level method, and letting it default to FtpRemoteExists.Overwrite.

I see I can probably use the low level methods to open a stream and set the file position to zero, but I really want to continue using high level calls if possible (my program uses FTP incidentally, not as a core feature).

Looking at your source again, you are right - FtpRemoteExists.NoCheck appears to do what I want, it bypasses all the checks and file delete and then sets the stream position to zero locally and remote. Thanks

**Comment by FanDjango** [comment]
> FluentFTP - 32.3.1

Ahso! Long time, **lots has changed**.

I have been researching this some more. The IBM FTP client, for example, allows you to

1. Either delete the file first (with a DELE client command) and then upload with STOR
or
2. Upload right away with STOR filepath (REPLACE, which will effectively not check for existance.

So, many clients have some way of letting the user choose the way to handle existing files on upload.

RFC for FTP STOR say that it should actually overwrite in place in all cases. But sadly, there are servers out there that will then prompt for overwrite allowance. It's a mess.

I think you should check if FtpRemoteExists.NoCheck will actually do the trick for you (because it has other ramifications, potentially), or if perhaps we might actually **add another** option to this flag to make this clearer. Keep me up to date on your results, please.

**Comment by mcrossley** [comment]
Thanks, I already offer the users the option to "delete before upload" to cover off those servers that do not allow direct over writing. What confused me was that FtpRemoteExists.Overwrite doesn't actually perform an over write, rather a delete + create, and you must use NoCheck to do an actual over write!

I have just checked my code and it is now working as I expected with...
```
conn.UploadStream(dataStream, remotefiletmp, DeleteBeforeUpload ? FtpRemoteExists.Overwrite : FtpRemoteExists.NoCheck);
```

Thanks for the help

**Comment by robinrodricks** [comment]
@FanDjango should we add another option like `OverwriteInPlace` which is a alias of `NoCheck`?

**Comment by FanDjango** [comment]
@robinrodricks Yeah, I think the same way. Bit unsure though about the original intent of NoCheck. I remember that it was created to make some users happy, that wanted to speed things up on uploads where they were **sure** that an upload would not fail, because they were sure the file does not exist.

As far as I can see, NoCheck will solve the @mcrossley problem, but I think it also makes resume impossible. ("ramifications")

OverWrite was coded in this way (with a check and if needed, a delete) to make a uploading a file with an existing one present on the server a no-brainer. But of course, the name OverWrite was a **misnomer**.

So, ** I would make OverWrite alias to NoCheck and try to fix the ensuing resume problem.**

I would then coin a new option for check and then delete (if needed), i.e. something like "SafeUpload".

**Comment by robinrodricks** [comment]
I would prefer not to change the behavior of Overwrite since so many users already use it.

**Comment by FanDjango** [comment]
Yes, I know. So, add the alias then. I was just describing how it got to this point.

**Comment by robinrodricks** [comment]
#### 50.1.0

 - **File Upload**
   - New: `FtpRemoteExists.OverwriteInPlace` mode which overwrites files without deleting them first
