### ISSUE TITLE
DownloadFile() overload to a Stream

### ISSUE THREAD

**Issue by natiki** [hgupta9/FluentFTP#35]
Hi Harsh,

Any chance of DownloadFile() overload with a Stream instead of to disk? Recipricol of #32.

**Comment by hgupta9** [comment]
I thought of that too, but I didn't know how to implement it. Would it create a new MemoryStream and return that? The byte[] version is obvious and can easily be implemented. However since its a different return type, an overload will be impossible. So the API will get a bit messed up:

- UploadFile() -- 3 overloads
- DownloadFile() -- download and save to disk
- DownloadFileAsBytes() -- new
- DownloadFileAsStream() -- new

**Comment by natiki** [comment]
How about out params that are either a stream or a byte array?

**Comment by hgupta9** [comment]
Okay so something like:

- DownloadFile(string, string)
- DownloadFile(string, out byte[])
- DownloadFile(string, out Stream)

Would that be discoverable? Anyways I think as an overload that should be pretty easy to discover. What do you think?

**Comment by natiki** [comment]
That looks good to me. It would come up nicely in code completion so be discoverable IMHO.

**Comment by hgupta9** [comment]
Done. Published to nuget as https://www.nuget.org/packages/FluentFTP/16.0.19

Sadly the byte[] and other versions appear in VS autocompletion before the string version. Do you know how to ask VS to prefer a certain overload?

**Comment by hgupta9** [comment]
Can you also test those methods to see if they work in your use case? I was going to use `out Stream` but decided to go with `Stream` since it allows the user to write data into any stream, whereas with `out Stream` I'm forced to create a new `MemoryStream` and set it into the var for C# to accept it.

**Comment by natiki** [comment]
Hi Harsh,

The stream version works for me in my use case. Only thing that may need consideration is that there is still an OverwriteFile parameter. This is redundant as the file is being written to a stream so I don't think that should be there anymore as a parameter.

**Comment by hgupta9** [comment]
Good points. Yes, I already discovered the overwrite parameter and removed it in the latest version.

**Comment by hgupta9** [comment]
I've made improvements to this in the latest version. You can fetch it from nuget. Can you see if everything works ok?

**Comment by jaxidian** [comment]
@hgupta9 Was this removed? I just updated to 17.x from 16.5.0 and I'm not seeing this in the 17.4.1 release. Was this moved to a different function or was it completely removed? If it was completely removed, can we get this back in? I'll be staying on 16.x until this works itself out.

**Comment by hgupta9** [comment]
@jaxidian Its now called Download() and Upload() for the stream/byte versions to make it more discoverable.

**Comment by jaxidian** [comment]
@hgupta9 Ahh, that'd be what I'm looking for. I could have sworn that I looked for renamed versions and couldn't find something - I guess I just didn't look hard enough. Thanks!
