### ISSUE TITLE
Implement FtpDataType in DownloadFile Method

### ISSUE THREAD

**Issue by Misaow** [hgupta9/FluentFTP#49]
Hello,

Would you consider implement a DownloadFile method with a "FtpDataType" as a parameter ?
Like this for example : `DownloadFile(string localPath, string remotePath, FtpDataType type, bool overwrite = true);`
Let me Explain : the method .OpenRead(...) is deprecated and we should use .DownloadFile(..) but, at the moment, we can't download files with 0 lenght with the method .DownloadFile(..).

Thank you for your response and your work,
Regards,

**Comment by hgupta9** [comment]
Continue using OpenRead since I have removed the Obsolete tag (will take effect next build). I will try to add the arg you requested.

**Comment by DJ-Cur** [comment]
@Misaow Thanks for you post, I'm having the same issue here. Did you find a way to download files with 0 length using OpenRead() ???

**Comment by hgupta9** [comment]
What do you need to happen when a file is zero-length? Would you like 0 bytes to be written to the stream? Currently [I'm throwing an exception](https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpClient.cs#L1995) for 0 length files.

**Comment by Misaow** [comment]
@hgupta9 : When a file is zero lenght (in my case some files are 0 lenght but contains text) i need a way to download these files. I opened this issue because the OpenRead Method is gonna be deprecated and then we'll have no way to download these files.
I put an example below to show you how i download these files at the moment.

@DJ-Cur  :  This is an example with DownloadFile method `client1DownloadFile(client1.OpenRead(item.FullName, FtpDataType.Binary), outputPath);`
This way you can download 0 lenght.

**Comment by DJ-Cur** [comment]
@hgupta9 : I'm having the same issue when downloading a textbased file (.txt, xml, etc) I get the same error telling me to try running the application using SetDataType() and FtpDataType.Binary. That can only work using OpenRead(), but for some reason when I use OpenRead() the stream I get has a length of 0 (But I know the file contains data). However I can still read this stream using StreamReader() but I'm not able to use system.IO.FileStream because a requirement is stream.length which is 0.
(Maybe relevant info: The server I'm downloading from supports binary transfer mode only)

Code:
Stream Stream = client.OpenRead(string path); 
FileStream fileStream = System.IO.File.Create(fileFullPath, (int)stream.Length); //(stream.length is 0, exception location)

       // Fill the bytes[] array with the stream data
        byte[] bytesInStream = new byte[stream.Length];
        stream.Read(bytesInStream, 0, (int)bytesInStream.Length);

        // Use FileStream object to write to the specified file
        fileStream.Write(bytesInStream, 0, bytesInStream.Length);
Maybe I'm doing something wrong, feel free to let me know.

@Misaow: I'm not sure that would work, assuming u meant FtpClient.DownloadFile() method, because the syntax is: 
public bool DownloadFile(Stream outStream, string remotePath);
public bool DownloadFile(out byte[] outBytes, string remotePath);
public bool DownloadFile(string localPath, string remotePath, bool overwrite = true);

The outputPath will not work at remotePath

**Comment by Misaow** [comment]
@DJ-Cur : Oh my Bad ! I'm sorry for my mistake. I just checked my project and in my case it work with the UploadFile method.
I didn't find a way to solve this actually.

**Comment by Misaow** [comment]
@hgupta9 : I edited my previous comments

**Comment by hgupta9** [comment]
Your error is something else (you just want to download a 0 length file) and you are asking for something else (FtpDataType). I don't think FtpDataType is required. I will just check and let you know if a 0 length file can be downloaded.

**Comment by hgupta9** [comment]
@DJ-Cur - Thanks for reporting this error. I'll work on it today.

**Comment by hgupta9** [comment]
I've released a version which supports uploading/downloaded of zero-length files. Can you see if that works for you?

https://www.nuget.org/packages/FluentFTP/16.2.2

**Comment by DJ-Cur** [comment]
@hgupta9 Thanks for the fast reply and new release. I've tried the new solution but unfortunately its downloading the files but they do not contain data. In other words they are all empty text files even though I'm sure the files contain data(text). 

The only way I got it to work is with this work around (which I'm not proud of haha)

Stream DownloadStream = client.OpenRead("RemotePath", FtpDataType.Binary);
                            StreamReader sr = new StreamReader(DownloadStream);
                            string file = sr.ReadToEnd();
                            File.WriteAllText("LocalPath", file);

For some reason this works fine, the System.IO.StreamReader seams to read these 0 Length files with no problem. But its not the best way to do it so I'm still looking for a better solution for this problem.

**Comment by hgupta9** [comment]
@DJ-Cur 
I really don't understand your use case. Are you trying to download a file which _has data_ and its downloading as zero length with DownloadFile()?? If so, then I think the error is that the **server is not reporting the length of the file.** Therefore my binary based reading does not work. Your code is not checking the length, you are simply reading until a NULL is encountered, which would work in some cases. Maybe I can add an option in DownloadFile() saying `readUptoNull` or `readZeroLenFiles` or something? What could be a simple name for this option, and how would it work? Only for certain file extensions? What is a sensible config? Because if I do this for all files, it could hang up in `ReadToEnd` method.

@Misaow 
Can you check the new version and see if it works for your use-case?

**Comment by DJ-Cur** [comment]
@hgupta9 Exactly you are correct in stating that the server is not reporting the length of the file. (see the FTPTrace below) in this test I've tried it with an .exe file. When I try the download with DownloadFile FluentFTP requests SIZE <file> . the server then returns with: 502 Command <SIZE curgasone.exe> not implemented.

TYPE I
200 Type set to I.
SIZE curgasone.exe
502 Command <SIZE curgasone.exe> not implemented.
PORT 10,10,10,36,209,203
200 Port command successful.
RETR curgasone.exe
150 Opening BINARY mode data connection.
550 RETR: Transfer failed.

When I download with Core FTP LE the trace looks like this:
TYPE I
200 Type set to I.
PORT 10,10,10,99,43,183
200 Port command successful.
STOR curgasone.exe
150 STOR: Command accepted!
226 Transfer Complete

I think ReadToEnd will only work with text based files (In my case it will work but I'm not sure I can download anything else)

Thanks for your fast reply, I hope this info. helps

**Comment by hgupta9** [comment]
@DJ-Cur - I don't understand the Core FTP logs - the STOR command is used to save a file to the server, not to download it. ([ref 1](https://en.wikipedia.org/wiki/List_of_FTP_commands), [ref 2](https://www.smartftp.com/support/kb/what-is-the-stor-command-f68.html)) The RETR command should been in the logs, which is used to download a file. Can you download a file with Core FTP and send those logs?

**Comment by DJ-Cur** [comment]
Yes you are correct, here it is

TYPE I  
200 Type set to I.  
PORT 10,10,10,99,44,5  
200 Port command successful.  
RETR z_TestFile5.xlsx  
150 Opening BINARY mode data connection.  
226 Transfer complete.  
z_TestFile5.xlsx - 6179 bytes transferred in 1 seconds  
Transfer time: 00:00:01

**Comment by hgupta9** [comment]
According to the [FTP docs](https://cr.yp.to/ftp/retr.html), your code is correct! 

>After sending the RETR request and reading a mark, the client reads data from the data connection until EOF (end of file), or a TCP error (for example, TCP reset or network unreachable), or timeout. The client saves the data, remembers whether there was a FIN, and closes the data connection. 

So the "read upto EOF" is basically a what `ReadToEnd()` does. I think I'll add an edge case handling for it. If the length of the file is reporting 0 by the server, then we will use this method.

**Comment by Misaow** [comment]
@hgupta9 : Works for me, Well done !

**Comment by hgupta9** [comment]
I've tried to implement a fix for you @DJ-Cur but before I publish it I need to confirm if everything is fine. Can you check this DLL and see if it works for your strange server?

https://we.tl/C3j9D3cWzq

**Comment by DJ-Cur** [comment]
@hgupta9 Great Work! Works good with my strange server :) 👍

**Comment by hgupta9** [comment]
Fantastic! This fix will be available in the next build I push to nuget.
