### ISSUE TITLE
Timed out trying to read data from the socket stream!

### ISSUE THREAD

**Issue by maxMakaronok** [hgupta9/FluentFTP#55]
Why this error happen on my virtual machine, but on my local it work good

Timed out trying to read data from the socket stream!

````
 ftpClient = new FtpClient
 {
                Host = settings.Host,
                Credentials = new NetworkCredential(settings.Login, settings.Password),
                EnableThreadSafeDataConnections = false,
                ReadTimeout = 30000,
                DataConnectionReadTimeout = 30000,
                DataConnectionType = FtpDataConnectionType.AutoActive     
 };
````

problem on windows server 2012 client

on windows 7 work good

**Comment by maxMakaronok** [comment]
windows server 2016 client error too

**Comment by hgupta9** [comment]
Which function are you using? DownloadFile?

**Comment by hgupta9** [comment]
Unless you reply its impossible to fix this.

**Comment by pbindy** [comment]
Hi,

I've just had this issue with the DeleteDirectory command.

**Comment by hgupta9** [comment]
@pbindy Can you share more details. Are there any files/folders in the dir you are trying to delete? Which server are you using? Azure has problems with timeouts...

**Comment by pbindy** [comment]
Hi,

here is my code
` if (FtpClient.DirectoryExists(folderPath))
          FtpClient.DeleteDirectory(folderPath, true, true);`

The folder has files in it, around 15. 

I'm trying to transfer from a PC with Windows 10 to a coffee machine with Windows CE installed.

This issue is not reproducible every time. I had the issue twice in a row and then nothing.

What I did to fix it, I make sure that the folder is empty (delete all files in it) before calling DeleteDirectory.

**Comment by hgupta9** [comment]
I see you are using the older version of FluentFTP. Can you upgrade to latest on nuget and check if it works for you?

**Comment by pbindy** [comment]
Ok I'll update to the latest version but there is definitely something happening with this DeleteDirectory method. (see #99 )

**Comment by hgupta9** [comment]
You don't need to delete the files in it first. Just call DeleteDirectory and see if its working good. Because we have switched to LIST command instead of machine listings and we are getting all files recursively, then deleting those files, then deleting the folder last. You should not have any problems.

**Comment by pbindy** [comment]
I'll check it once again but I need to make a lot of testing before putting it in Production because it has to work 100% of the time.

**Comment by hgupta9** [comment]
Closing this since no response received from OP.

**Comment by gjhdigital** [comment]
I realized this just got closed 4 hours ago, But I just ran into this issue today. I updated to the latest version v17.3.0 and I am still getting this error message when attempting to us FTPS using the code provided here: https://github.com/hgupta9/FluentFTP#faq_ftps

**Comment by hgupta9** [comment]
@gjhdigital Okay, issue reopened. Which FTP server/OS are you using? or which host?

**Comment by gjhdigital** [comment]
nevermind, wrong protocol.

**Comment by hgupta9** [comment]
@gjhdigital What was the solution so others can know?

**Comment by gjhdigital** [comment]
I was told the connection was FTPS when it was actually SFTP. So I ended up using the recommended SSH.NET package. Im using FluentFTP for another project and it works flawlessly for that.

**Comment by hgupta9** [comment]
@gjhdigital Excellent, thank you.
